#ifndef CHESS_OFFSET_H_INCLUDED
#define CHESS_OFFSET_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

#include <chess/macros.h>
#include <chess/square.h>

#include <stdint.h>

CHESS_ENUM(int8_t, ChessOffset) {
	CHESS_OFFSET_NORTH      = CHESS_SQUARE_A2 - CHESS_SQUARE_A1,
	CHESS_OFFSET_EAST       = CHESS_SQUARE_B1 - CHESS_SQUARE_A1,
	CHESS_OFFSET_SOUTH      = -CHESS_OFFSET_NORTH,
	CHESS_OFFSET_WEST       = -CHESS_OFFSET_EAST,

	CHESS_OFFSET_NORTH_EAST = CHESS_OFFSET_NORTH + CHESS_OFFSET_EAST,
	CHESS_OFFSET_SOUTH_EAST = CHESS_OFFSET_SOUTH + CHESS_OFFSET_EAST,
	CHESS_OFFSET_SOUTH_WEST = CHESS_OFFSET_SOUTH + CHESS_OFFSET_WEST,
	CHESS_OFFSET_NORTH_WEST = CHESS_OFFSET_NORTH + CHESS_OFFSET_WEST,
};

#ifdef __cplusplus
}
#endif

#endif // CHESS_OFFSET_H_INCLUDED
