#include <chess.h>

enum chess_direction : int8_t {
	CHESS_DIRECTION_NORTH = CHESS_SQUARE_A2 - CHESS_SQUARE_A1,
	CHESS_DIRECTION_EAST = CHESS_SQUARE_B1 - CHESS_SQUARE_A1,
	CHESS_DIRECTION_SOUTH = -CHESS_DIRECTION_NORTH,
	CHESS_DIRECTION_WEST = -CHESS_DIRECTION_EAST,

	CHESS_DIRECTION_NORTH_EAST = CHESS_DIRECTION_NORTH + CHESS_DIRECTION_EAST,
	CHESS_DIRECTION_SOUTH_EAST = CHESS_DIRECTION_SOUTH + CHESS_DIRECTION_EAST,
	CHESS_DIRECTION_SOUTH_WEST = CHESS_DIRECTION_SOUTH + CHESS_DIRECTION_WEST,
	CHESS_DIRECTION_NORTH_WEST = CHESS_DIRECTION_NORTH + CHESS_DIRECTION_WEST,
};
